### ISSUE TITLE
R-Python Comparison

### ISSUE THREAD

**Issue by AlbertoAlmuinha** [FedericoGarza/tsfeatures#13]
Hi,

In the section "Comparison with the R implementation (sum of absolute differences)" of the README, differences in some features between the Python and R implementations can be seen, however, for other features the differences are 0. 

In my own dataset I also observe differences in other features (trend, for example) and I would like to know what these differences are due to and why the results do not match between the two implementations.

Are different implementations being used? I just want to be clear about the reason for the differences.

Thanks for the work on this package!

**Comment by AzulGarza** [comment]
Hi, Alberto! 

Thanks for using the package.

In some cases, differences can arise due to the underlying implementation of certain functions differing for python and R. For example, the trend feature uses the python package  `supersmoother`, which, to our knowledge, has minor differences to the R implementation.  The same occurs for features based on `statsmodels` functions. 

Thank you!

**Comment by AlbertoAlmuinha** [comment]
Thanks for the answer @FedericoGarza !

That makes perfect sense, so I close the issue.
